# Generated by Django 2.2 on 2020-09-02 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='short_url',
            new_name='ShortUrl',
        ),
    ]
